In [1]:
#Reshaping Data

import numpy as np

a = np.random.randint(1,50,12)
a

array([37, 13, 20,  7, 31, 46, 28, 28, 18, 15, 17,  4])

In [2]:
a.shape

(12,)

In [3]:
a = a.reshape(2,6)
a

array([[37, 13, 20,  7, 31, 46],
       [28, 28, 18, 15, 17,  4]])

In [5]:
a = a.reshape(6,2)
a

array([[37, 13],
       [20,  7],
       [31, 46],
       [28, 28],
       [18, 15],
       [17,  4]])

In [6]:
a = a.reshape(3,4)
a

array([[37, 13, 20,  7],
       [31, 46, 28, 28],
       [18, 15, 17,  4]])

In [7]:
a = a.reshape(4,3)
a

array([[37, 13, 20],
       [ 7, 31, 46],
       [28, 28, 18],
       [15, 17,  4]])

In [9]:
# Principal of -1

a = a.reshape(-1,4)
a

array([[37, 13, 20,  7],
       [31, 46, 28, 28],
       [18, 15, 17,  4]])

In [11]:
#Seed Function () ==> We know that randint function generates random numbers.
#Everytime we run the program, nw set of random number is generated.
#So, solve this program we will use seed function.

In [12]:
import numpy as np

np.random.seed(12)
a = np.random.randint(1,100,10)
a

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [13]:
# View vs Copy ==> When we slice a sub-array from an array, it maybe done by two ways.

In [16]:
import numpy as np
a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6]
b[:] = 0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [17]:
# Copy

a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6].copy()
b[:] = 0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [20]:
# Condional Selection

import numpy as np 
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [22]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [23]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [24]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [28]:
# Operations on Array

import numpy as np
a = np.arange(1,5)
a*2



array([2, 4, 6, 8])

In [29]:
a + 2

array([3, 4, 5, 6])

In [30]:
a ** 2

array([ 1,  4,  9, 16])

In [31]:
a = np.array([1,2,3,4,]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [32]:
b = np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [33]:
a+b

array([[ 6,  8],
       [10, 12]])

In [34]:
a-b

array([[-4, -4],
       [-4, -4]])

In [35]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [36]:
a*b

array([[ 5, 12],
       [21, 32]])

In [37]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [38]:
# Linspace() ==> This function returns value between a given range  and with  a  same gap between consicutive elements. 

In [41]:
import numpy as np

a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [43]:
import numpy as np 

np.random.seed(122)
a = np.random.randint(1,21,9).reshape(3,3)
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [44]:
#np.unique(arr , return_index = True , return_counts = True

#return 3 array.

#1. the array with unique values
#2. the array with respective index value
#3. the array with counting of frequencey

In [45]:
a = np.array([10,20,30,40,10,20,50])
np.unique(a , return_index = True , return_counts = True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 6], dtype=int64),
 array([2, 2, 1, 1, 1], dtype=int64))

In [46]:
# Horizontal and Vertical Stacking

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [47]:
b

array([5, 6, 7, 8])

In [48]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])