In [1]:
# One Dimensional Array

import numpy as np
a = [1,2,3,4,5]
b = np.array(a)
b

array([1, 2, 3, 4, 5])

In [3]:
a = []
size = int(input("enter size"))
for i in range(size):
  val = int(input("enter number"))
  a.append(val)
  print(a)
  b = np.array(a)
  b

enter size3
enter number4
[4]
enter number5
[4, 5]
enter number4
[4, 5, 4]


In [5]:
# Two Dimensional Array

a = [[1,2,3] , [4,5,6] , [7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# how to check size and dimensional of an array ?


In [10]:
a = [[1,2,3] , [4,5,6] , [7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
print("Total Dimension = " , b.ndim)

Total Dimension =  2


In [14]:
print("Total Rows And Columns = " , b.shape)

Total Rows And Columns =  (3, 3)


In [ ]:
# Numpy Function >>>

1. Zeros ==> This Function create an array
 (either one demensional or multi dimensional )
and fill all the value with zeros.

In [15]:
import numpy as np
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [16]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
b.ndim

2

In [19]:
# 2. one ==> This function creats an array (either one dimensional or multi dimensioanl ) and fill all the values with one.

In [20]:
import numpy as np
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [22]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
# 3. eye ==> This function creats an array with all the digonal elements as 1 and rest are 0(in square matrix). In non-square matrix the value are still one for digonal (upto which it can draw digonal ) and rest are zero.

In [24]:
import numpy as np
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
b = np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [26]:
# 4. diagonal ==> This function creats a two dimensional array with all the digonal elements as the given value and rest are zero.

In [27]:
import numpy as np
a = np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [28]:
# 5.randint ==> This function is used to generate a random number between a given range.

# syntax == randint(min_value , max_value , total_number)

In [29]:
import numpy as np
a = np.random.randint(1,10,3)
a

array([9, 7, 2])

In [30]:
# rand() ==> This function is used to generate a random number between 0 to 1.
# syntax == rand(number of values)

In [33]:
import numpy as np

a = np.random.rand(5)
a

array([0.10745146, 0.90182791, 0.78718355, 0.29094415, 0.01207939])